### ISSUE TITLE
Hosted build pools have licensed version of Xamarin

### ISSUE THREAD

**Issue by chrispat** [Microsoft-Build-2016/CodeLabs-MobileDevOps#3]
Currently the hosted build pools have a licensed version of Xamarin.  We are in process of installing the new builds that do not require a license and we expect to have that complete by end of week.

**Comment by nzthiago** [comment]
Thanks @chrisrpatterson let us know once it's been updated and tested and we can update the code labs instructions so they can use the hosted build for the builds

**Comment by azchohfi** [comment]
I'm still facing this problem on my Hosted Build's. @chrisrpatterson, any update?
